name: Build-And-Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        run: rm -rf node_modules
      - name: Prebuild - get version
        shell: bash
        run: |
          VERSION=$(node -e 'fs=require("fs");console.log(JSON.parse(fs.readFileSync("package.json")).dependencies.kuzu)')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kuzudb/api-server:latest, kuzudb/api-server:${{ env.VERSION }}
          build-args: |
            SKIP_GRAMMAR=true
            SKIP_BUILD_APP=true
            SKIP_DATASETS=true
